"""
Problem 12:
The sequence of triangle numbers is generated by adding the natural numbers.
What is the value of the first triangle number to have over five hundred divisors?
"""
import math
def compute():
  i = 1
  while True:
    triangle_num = sum_of_n(i)
    if count_divisors(triangle_num)>500:
      return triangle_num
    i+=1
def sum_of_n(n):
  s = (n/2)*(n+1)
  return s

def count_divisors(n):
  count = 0
  for i in range(1, int(math.sqrt(n)+1)):
    if n % i == 0:
      if i * i == n:
        count += 1
      else:
        count += 2
  return count
  
print(compute())