'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with and, the first terms will be:
 1, 2, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
f_n = 2
f_n_1 = 1
f_n_2 = 1
s = 0
while (f_n < 4*10**6):
    f_n = f_n_1 + f_n_2
    if (f_n % 2 == 0):
        s += f_n
    f_n_2 = f_n_1
    f_n_1 = f_n

print(s)